# Generated by Django 6.0.1 on 2026-01-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='modelo',
            field=models.CharField(default='padrão', max_length=100),
        ),
    ]
