# Generated by Django 6.0.1 on 2026-01-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0002_encomenda_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
    ]
