# Generated by Django 6.0.1 on 2026-01-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0003_alter_encomenda_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecido',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
