# Generated by Django 6.0.1 on 2026-01-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0004_alter_tecido_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecido',
            name='cor',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tecido',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
