# Generated by Django 6.0.1 on 2026-01-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0005_alter_tecido_cor_alter_tecido_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tecido',
            unique_together={('nome', 'cor')},
        ),
    ]
