# Generated by Django 6.0.1 on 2026-01-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0006_alter_tecido_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
