# Generated by Django 6.0.1 on 2026-01-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0007_encomenda_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
