# Generated by Django 6.0.1 on 2026-02-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0008_encomenda_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=10),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='metragem',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
