# Generated by Django 6.0.1 on 2026-03-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0009_encomenda_status_alter_encomenda_metragem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
