# Generated by Django 6.0.1 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0010_encomenda_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecido',
            name='cor',
            field=models.CharField(max_length=100),
        ),
    ]
